### ISSUE TITLE
Truncate sonata breadcrumb 

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/fibervent#2]
@davidromani when the auditWindmillBlade list name's is too long, it hides the next sonata block as it shows at the picture:
![captura de pantalla 2016-09-08 a les 23 58 50](https://cloud.githubusercontent.com/assets/12971681/18370245/f805c238-762b-11e6-8552-4b5ae9a02065.png)
I tryied to solve overwriting the {%block sonata_breadcrumb%} through a truncate, but i don't think it's the best way because it depends of the length of each label.
![captura de pantalla 2016-09-09 a les 1 36 06](https://cloud.githubusercontent.com/assets/12971681/18370532/0a44c398-762e-11e6-83c0-1792c597c744.png)
Some idea?

**Comment by davidromani** [comment]
Maybe you can count the total length of all labels, and then decide if you need to truncate or not the last one. Twig can set a counter variable to sum all labels length.
