### ISSUE TITLE
Call a method from twig

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/fibervent#3]
@davidromani 

I don't know...

![image](https://cloud.githubusercontent.com/assets/12971681/18730327/0f39a8b4-8056-11e6-98f6-7e9d63ea9c1d.png)

**Comment by davidromani** [comment]
My was example was for a **1** auditWindmillBlade, but in this case you have a collection of auditWindmillBlades. So you need to iterate all the aduits.
